title: Vlad Ku

description: "Статьи по HTML, CSS, SASS, LESS, JS, jQuery, node.js и многое другое"
baseurl: ""
url: "http://vlad-ku.ru"

plugins:
  - jekyll-sitemap

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  # - node_modules
  # - LICENSE
  # - README.md

# permalink: /:title/
permalink: /:year:month:day-:title/

paginate: 5
paginate_path: "/page:num/"
